import dotenv from "dotenv";
import mongoose from "mongoose";
import Product from "./models/Product.js";

dotenv.config();

const TECH_CATEGORY_ID = "691f8adadb32292734576db2";

const products = [
  {
    name: "Cargador Note 9 TC",
    description:
      "Cargador Samsung Galaxy Note 9 con conector tipo C, carga rápida y eficiente",
    price: 11000,
    stock: 1,
    featured: false,
    ingredients: [
      "Compatible con Samsung Galaxy Note 9",
      "Conector USB Tipo-C",
      "Cable de 1 metro",
      "Certificación de seguridad",
    ],
    benefits: [
      "Carga rápida y segura",
      "Cable resistente",
      "Protección contra sobrecarga",
      "Compatible con otros dispositivos USB-C",
    ],
  },
  {
    name: "Cargador Samsung 3.0A V8",
    description:
      "Cargador Samsung de carga rápida 3.0A con conector V8 (Micro USB)",
    price: 11000,
    stock: 1,
    featured: false,
    ingredients: [
      "Salida de 3.0A",
      "Conector Micro USB V8",
      "Cable de 1 metro",
      "Compatible con Samsung",
    ],
    benefits: [
      "Carga rápida 3.0A",
      "Universal Micro USB",
      "Duradero y resistente",
      "Protección integrada",
    ],
  },
  {
    name: "Cargador Samsung 3.0A TC",
    description: "Cargador Samsung de carga rápida 3.0A con conector tipo C",
    price: 11000,
    stock: 1,
    featured: false,
    ingredients: [
      "Salida de 3.0A",
      "Conector USB Tipo-C",
      "Cable de 1 metro",
      "Compatible con Samsung",
    ],
    benefits: [
      "Carga rápida 3.0A",
      "Conector reversible",
      "Mayor durabilidad",
      "Transferencia de datos rápida",
    ],
  },
  {
    name: "Cargador Moto Turbo V8",
    description: "Cargador Motorola Turbo Power con conector Micro USB V8",
    price: 13000,
    stock: 1,
    featured: false,
    ingredients: [
      "Tecnología Turbo Power",
      "Conector Micro USB V8",
      "Carga ultra rápida",
      "Compatible con Motorola",
    ],
    benefits: [
      "Carga turbo en minutos",
      "Ahorro de tiempo",
      "Compatibilidad universal",
      "Diseño compacto",
    ],
  },
  {
    name: "Cargador Moto Turbo TC",
    description: "Cargador Motorola Turbo Power con conector tipo C",
    price: 14000,
    stock: 1,
    featured: false,
    ingredients: [
      "Tecnología Turbo Power",
      "Conector USB Tipo-C",
      "Carga ultra rápida",
      "Compatible con Motorola",
    ],
    benefits: [
      "Carga turbo ultra rápida",
      "Conector reversible",
      "Mayor eficiencia energética",
      "Protección avanzada",
    ],
  },
  {
    name: "Cargador Samsung S20-5G V8",
    description: "Cargador Samsung Galaxy S20 5G con conector Micro USB V8",
    price: 14000,
    stock: 1,
    featured: false,
    ingredients: [
      "Compatible con S20 5G",
      "Conector Micro USB V8",
      "Carga rápida",
      "Alta calidad",
    ],
    benefits: [
      "Optimizado para 5G",
      "Carga estable",
      "Compatible con múltiples modelos",
      "Diseño elegante",
    ],
  },
  {
    name: "Cargador Samsung S20-5G TC",
    description: "Cargador Samsung Galaxy S20 5G con conector tipo C",
    price: 15000,
    stock: 1,
    featured: false,
    ingredients: [
      "Compatible con S20 5G",
      "Conector USB Tipo-C",
      "Carga rápida",
      "Cable reforzado",
    ],
    benefits: [
      "Carga super rápida",
      "Tecnología 5G compatible",
      "Mayor vida útil",
      "Conexión segura",
    ],
  },
  {
    name: "Cargador Samsung S22 50W TC-TC",
    description: "Cargador Samsung Galaxy S22 de 50W con doble conector tipo C",
    price: 28000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia de 50W",
      "Doble USB Tipo-C",
      "Super Fast Charging 2.0",
      "Compatible con S22",
    ],
    benefits: [
      "Carga ultra rápida 50W",
      "Máxima velocidad de carga",
      "Tecnología de punta",
      "Carga completa en minutos",
    ],
  },
  {
    name: "Cargador Xiaomi 67W V8",
    description: "Cargador Xiaomi HyperCharge de 67W con conector Micro USB V8",
    price: 21000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia de 67W",
      "Tecnología HyperCharge",
      "Conector Micro USB V8",
      "Compatible con Xiaomi",
    ],
    benefits: [
      "Carga extremadamente rápida",
      "Tecnología HyperCharge",
      "Eficiencia máxima",
      "Menor tiempo de carga",
    ],
  },
  {
    name: "Cargador Xiaomi 67W TC",
    description: "Cargador Xiaomi HyperCharge de 67W con conector tipo C",
    price: 22000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia de 67W",
      "Tecnología HyperCharge",
      "Conector USB Tipo-C",
      "Compatible con Xiaomi",
    ],
    benefits: [
      "Carga ultra rápida 67W",
      "HyperCharge avanzado",
      "Conector reversible",
      "Mayor durabilidad",
    ],
  },
  {
    name: "Cargador Xiaomi 67W TC-TC",
    description: "Cargador Xiaomi HyperCharge de 67W con doble conector tipo C",
    price: 30000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia de 67W",
      "Doble USB Tipo-C",
      "Tecnología HyperCharge",
      "Cable premium",
    ],
    benefits: [
      "Máxima velocidad de carga",
      "Doble puerto USB-C",
      "Carga múltiples dispositivos",
      "Calidad premium",
    ],
  },
  {
    name: "Cargador Samsung 67W V8",
    description: "Cargador Samsung de 67W con conector Micro USB V8",
    price: 21000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia de 67W",
      "Conector Micro USB V8",
      "Super Fast Charging",
      "Compatible con Samsung",
    ],
    benefits: [
      "Carga ultra rápida",
      "Alta potencia",
      "Compatibilidad amplia",
      "Seguridad garantizada",
    ],
  },
  {
    name: "Cargador Samsung 67W TC",
    description: "Cargador Samsung de 67W con conector tipo C",
    price: 22000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia de 67W",
      "Conector USB Tipo-C",
      "Super Fast Charging",
      "Cable resistente",
    ],
    benefits: [
      "Carga super rápida",
      "Tecnología avanzada",
      "Mayor eficiencia",
      "Protección inteligente",
    ],
  },
  {
    name: "Cargador Samsung 67W TC-TC",
    description: "Cargador Samsung de 67W con doble conector tipo C",
    price: 30000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia de 67W",
      "Doble USB Tipo-C",
      "Super Fast Charging 2.0",
      "Premium quality",
    ],
    benefits: [
      "Máxima potencia de carga",
      "Doble conector",
      "Versatilidad total",
      "Calidad superior",
    ],
  },
  {
    name: "Cargador iPhone 5W",
    description: "Cargador Apple iPhone de 5W original con cable Lightning",
    price: 12000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia de 5W",
      "Cable Lightning",
      "Compatible con iPhone",
      "Diseño original Apple",
    ],
    benefits: [
      "Carga segura certificada",
      "Compatible con todos los iPhone",
      "Diseño compacto",
      "Calidad Apple",
    ],
  },
  {
    name: "Cargador iPhone 25W",
    description:
      "Cargador Apple iPhone de 25W de carga rápida con cable Lightning",
    price: 28000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia de 25W",
      "Cable Lightning",
      "Fast Charging",
      "Compatible iPhone 12 y superiores",
    ],
    benefits: [
      "Carga rápida certificada",
      "Mayor velocidad",
      "Optimizado para iPhone",
      "Máxima compatibilidad",
    ],
  },
  {
    name: "Manos Libres Lenteja HS330",
    description:
      "Auriculares manos libres tipo lenteja HS330, compactos y cómodos",
    price: 4400,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño tipo lenteja",
      "Micrófono integrado",
      "Conector 3.5mm",
      "Cable resistente",
    ],
    benefits: [
      "Ultra compactos",
      "Cómodos de usar",
      "Buena calidad de audio",
      "Económicos y prácticos",
    ],
  },
  {
    name: "Manos Libres S8 AKG",
    description: "Auriculares Samsung S8 AKG, audio de alta calidad",
    price: 6000,
    stock: 1,
    featured: false,
    ingredients: [
      "Tecnología AKG",
      "Diseño ergonómico",
      "Graves potentes",
      "Compatible con Samsung",
    ],
    benefits: [
      "Audio premium AKG",
      "Excelente calidad de sonido",
      "Comodidad superior",
      "Graves profundos",
    ],
  },
  {
    name: "Diadema AirPods Max",
    description:
      "Audífonos tipo diadema estilo AirPods Max con cancelación de ruido",
    price: 140000,
    stock: 1,
    featured: false,
    ingredients: [
      "Cancelación activa de ruido",
      "Audio espacial",
      "Bluetooth 5.0",
      "Batería de larga duración",
    ],
    benefits: [
      "Cancelación de ruido premium",
      "Audio inmersivo",
      "Comodidad todo el día",
      "Diseño elegante",
    ],
  },
  {
    name: "Reloj Inteligente HK9 Mini",
    description:
      "Smartwatch HK9 Mini con múltiples funciones deportivas y de salud",
    price: 140000,
    stock: 1,
    featured: false,
    ingredients: [
      "Pantalla HD",
      "Monitor de frecuencia cardíaca",
      "Modos deportivos",
      "Resistente al agua IP67",
    ],
    benefits: [
      "Monitoreo de salud 24/7",
      "Notificaciones inteligentes",
      "Batería de larga duración",
      "Diseño elegante",
    ],
  },
  {
    name: "Reloj Inteligente HK10 Mini",
    description: "Smartwatch HK10 Mini con pantalla mejorada y más funciones",
    price: 160000,
    stock: 1,
    featured: false,
    ingredients: [
      "Pantalla AMOLED",
      "Monitor de oxígeno en sangre",
      "GPS integrado",
      "Resistente al agua IP68",
    ],
    benefits: [
      "Pantalla más nítida",
      "Más modos deportivos",
      "Seguimiento GPS preciso",
      "Mayor resistencia al agua",
    ],
  },
  {
    name: "Reloj Inteligente JS WATCH10 Pro+",
    description: "Smartwatch JS WATCH10 Pro+ premium con funciones avanzadas",
    price: 220000,
    stock: 1,
    featured: false,
    ingredients: [
      'Pantalla AMOLED 1.96"',
      "Llamadas Bluetooth",
      "Monitor completo de salud",
      "Múltiples esferas",
    ],
    benefits: [
      "Realiza y recibe llamadas",
      "Monitoreo avanzado",
      "Pantalla grande y clara",
      "Múltiples opciones de personalización",
    ],
  },
  {
    name: "Reloj Inteligente JS WATCH 10 Mini",
    description:
      "Smartwatch JS WATCH 10 Mini compacto con máximas prestaciones",
    price: 240000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño compacto premium",
      "Pantalla retina",
      "Asistente de voz",
      "Sensor de temperatura",
    ],
    benefits: [
      "Diseño elegante",
      "Tecnología de punta",
      "Control por voz",
      "Monitoreo completo de salud",
    ],
  },
  {
    name: "Reloj Inteligente HK10 Ultra3",
    description:
      "Smartwatch HK10 Ultra3 con diseño similar a Apple Watch Ultra",
    price: 230000,
    stock: 1,
    featured: false,
    ingredients: [
      'Pantalla 2.0" HD',
      "Corona digital",
      "Ultra resistente",
      "Batería de 7 días",
    ],
    benefits: [
      "Diseño robusto premium",
      "Pantalla extra grande",
      "Batería ultra duradera",
      "Para deportes extremos",
    ],
  },
  {
    name: "Reloj Inteligente HK11 ULTRA3",
    description:
      "Smartwatch HK11 ULTRA3 última generación con todas las funciones",
    price: 250000,
    stock: 1,
    featured: false,
    ingredients: [
      "Última generación",
      'Pantalla 2.1" AMOLED',
      "Sensor de temperatura corporal",
      "ECG completo",
    ],
    benefits: [
      "Tecnología más avanzada",
      "Monitoreo médico completo",
      "Máximo rendimiento",
      "Calidad superior",
    ],
  },
  {
    name: "Reloj Inteligente HK11 PRO MAX",
    description:
      "Smartwatch HK11 PRO MAX versión premium con máximas características",
    price: 240000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño PRO MAX",
      "Pantalla curva 3D",
      "Carga inalámbrica",
      "NFC integrado",
    ],
    benefits: [
      "Diseño ultra premium",
      "Carga sin cables",
      "Pagos contactless",
      "Experiencia de lujo",
    ],
  },
  {
    name: "Reloj Inteligente Hello Plum",
    description:
      "Smartwatch Hello Plum con diseño moderno y funciones completas",
    price: 240000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño elegante",
      "Múltiples modos deportivos",
      "Monitor de sueño avanzado",
      "Resistente al agua",
    ],
    benefits: [
      "Estilo único",
      "Análisis de sueño detallado",
      "Gran autonomía",
      "Interfaz amigable",
    ],
  },
  {
    name: "Parlante JBL XTREM4 Mini",
    description:
      "Bocina portátil JBL XTREM4 Mini con sonido potente y resistente al agua",
    price: 96000,
    stock: 1,
    featured: false,
    ingredients: [
      "Sonido JBL Pro",
      "Bluetooth 5.3",
      "Resistente al agua IPX7",
      "Batería 12 horas",
    ],
    benefits: [
      "Sonido potente y claro",
      "Portátil y resistente",
      "Ideal para exteriores",
      "Graves profundos",
    ],
  },
  {
    name: "Parlante JBL FLIP7",
    description: "Bocina JBL FLIP7 con audio 360° y batería de larga duración",
    price: 100000,
    stock: 1,
    featured: false,
    ingredients: [
      "Audio 360 grados",
      "Bluetooth multiconexión",
      "IPX7 impermeable",
      "Batería 15 horas",
    ],
    benefits: [
      "Sonido envolvente",
      "Conecta múltiples dispositivos",
      "Totalmente impermeable",
      "Batería duradera",
    ],
  },
  {
    name: "Cable PELKING CB-P01 V8",
    description: "Cable USB a Micro USB V8 marca PELKING de alta calidad",
    price: 4000,
    stock: 1,
    featured: false,
    ingredients: [
      "Cable Micro USB",
      "Longitud 1 metro",
      "Carga y datos",
      "Material resistente",
    ],
    benefits: [
      "Carga rápida",
      "Transferencia de datos",
      "Cable duradero",
      "Buen precio",
    ],
  },
  {
    name: "Cable PELKING PCB-100 V8",
    description: "Cable USB a Micro USB V8 PELKING PCB-100 reforzado",
    price: 7000,
    stock: 1,
    featured: false,
    ingredients: [
      "Cable reforzado",
      "Micro USB V8",
      "Nylon trenzado",
      "1.2 metros",
    ],
    benefits: [
      "Extra resistente",
      "No se enreda",
      "Mayor durabilidad",
      "Carga rápida mejorada",
    ],
  },
  {
    name: "Cable PELKING PCB-100 TC",
    description: "Cable USB a Tipo C PELKING PCB-100 reforzado",
    price: 7000,
    stock: 1,
    featured: false,
    ingredients: [
      "Cable reforzado",
      "USB Tipo-C",
      "Nylon trenzado",
      "1.2 metros",
    ],
    benefits: [
      "Conector reversible",
      "Extra duradero",
      "Carga rápida",
      "Transferencia rápida de datos",
    ],
  },
  {
    name: "Pulso Nike 38mm-40mm",
    description: "Correa estilo Nike para smartwatch de 38mm y 40mm",
    price: 9000,
    stock: 1,
    featured: false,
    ingredients: [
      "Compatible 38mm-40mm",
      "Material deportivo",
      "Diseño Nike",
      "Transpirable",
    ],
    benefits: [
      "Cómodo para deporte",
      "Diseño deportivo",
      "Transpirable",
      "Fácil de limpiar",
    ],
  },
  {
    name: "Pulso Nike 42mm-45mm",
    description: "Correa estilo Nike para smartwatch de 42mm y 45mm",
    price: 9000,
    stock: 1,
    featured: false,
    ingredients: [
      "Compatible 42mm-45mm",
      "Material deportivo",
      "Diseño Nike",
      "Transpirable",
    ],
    benefits: [
      "Perfecto para ejercicio",
      "Estilo deportivo premium",
      "Alta transpirabilidad",
      "Resistente al sudor",
    ],
  },
  {
    name: "Pulso Liso para Smartwatch",
    description: "Correa lisa universal para smartwatch, diseño minimalista",
    price: 8000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño liso",
      "Silicona suave",
      "Universal",
      "Varios colores",
    ],
    benefits: [
      "Diseño elegante",
      "Cómodo todo el día",
      "Fácil instalación",
      "Versátil",
    ],
  },
  {
    name: "Pulso Oceans para Smartwatch",
    description: "Correa Oceans para smartwatch con diseño marino",
    price: 8000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño Oceans",
      "Silicona premium",
      "Resistente al agua",
      "Colores vibrantes",
    ],
    benefits: [
      "Diseño único",
      "Impermeable",
      "Colores llamativos",
      "Muy cómodo",
    ],
  },
  {
    name: "Pulso Velcro para Smartwatch",
    description: "Correa tipo velcro ajustable para smartwatch",
    price: 12000,
    stock: 1,
    featured: false,
    ingredients: [
      "Sistema velcro",
      "Ajuste total",
      "Material nylon",
      "Muy ligero",
    ],
    benefits: [
      "Ajuste perfecto",
      "Ultra ligero",
      "Fácil de poner y quitar",
      "Muy resistente",
    ],
  },
  {
    name: "Pulso Metálico para Smartwatch",
    description: "Correa metálica premium para smartwatch, estilo elegante",
    price: 16000,
    stock: 1,
    featured: false,
    ingredients: [
      "Acero inoxidable",
      "Eslabones ajustables",
      "Cierre de seguridad",
      "Acabado premium",
    ],
    benefits: [
      "Look elegante y formal",
      "Muy duradero",
      "No causa alergias",
      "Ajustable a cualquier muñeca",
    ],
  },
  {
    name: "Protector Cargador 20W iPhone",
    description: "Funda protectora para cargador iPhone de 20W",
    price: 10000,
    stock: 1,
    featured: false,
    ingredients: [
      "Compatible con cargador 20W",
      "Silicona suave",
      "Anti golpes",
      "Varios colores",
    ],
    benefits: [
      "Protege tu cargador",
      "Evita daños",
      "Fácil identificación",
      "Mayor durabilidad del cargador",
    ],
  },
  {
    name: "Vidrio Templado 21D",
    description:
      "Protector de pantalla vidrio templado 21D con cobertura total",
    price: 1400,
    stock: 1,
    featured: false,
    ingredients: [
      "Vidrio templado 21D",
      "Cobertura completa",
      "Dureza 9H",
      "Fácil instalación",
    ],
    benefits: [
      "Protección total",
      "Máxima resistencia",
      "Tacto suave",
      "Transparencia perfecta",
    ],
  },
  {
    name: "Vidrio Cerámica Matte",
    description:
      "Protector de pantalla de cerámica con acabado mate anti reflejos",
    price: 1400,
    stock: 1,
    featured: false,
    ingredients: [
      "Cerámica premium",
      "Acabado mate",
      "Anti reflejos",
      "Dureza superior",
    ],
    benefits: [
      "Reduce reflejos",
      "Sensación suave",
      "Resistencia extrema",
      "Anti huellas",
    ],
  },
  {
    name: "Vidrio Premium",
    description:
      "Protector de pantalla vidrio templado premium de alta calidad",
    price: 2400,
    stock: 1,
    featured: false,
    ingredients: [
      "Vidrio templado premium",
      "Dureza 9H+",
      "Ultra delgado",
      "Resistente a rayones",
    ],
    benefits: [
      "Calidad superior",
      "Protección avanzada",
      "Claridad HD",
      "Fácil limpieza",
    ],
  },
  {
    name: "Vidrio Premium Antiespia",
    description:
      "Protector de pantalla premium con filtro de privacidad antiespia",
    price: 3000,
    stock: 1,
    featured: false,
    ingredients: [
      "Filtro de privacidad",
      "Vidrio templado",
      "Ángulo de visión 28°",
      "Anti reflejos",
    ],
    benefits: [
      "Máxima privacidad",
      "Nadie ve tu pantalla",
      "Protección completa",
      "Ideal para trabajo",
    ],
  },
  {
    name: "AirPods Max Réplica",
    description:
      "Audífonos tipo diadema estilo AirPods Max con excelente calidad",
    price: 140000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño AirPods Max",
      "Cancelación de ruido",
      "Audio espacial",
      "Batería 20 horas",
    ],
    benefits: [
      "Diseño premium Apple",
      "Audio inmersivo",
      "Comodidad extrema",
      "Cancelación activa de ruido",
    ],
  },
  {
    name: "AirPods 1/2 Réplica",
    description: "Audífonos inalámbricos estilo AirPods generación 1 y 2",
    price: 48000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño AirPods",
      "Bluetooth 5.0",
      "Estuche de carga",
      "Sonido estéreo",
    ],
    benefits: [
      "Diseño icónico",
      "Fácil conexión",
      "Portabilidad máxima",
      "Buena autonomía",
    ],
  },
  {
    name: "AirPods Serie 3 Réplica",
    description: "Audífonos inalámbricos estilo AirPods generación 3",
    price: 52000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño AirPods 3",
      "Audio espacial",
      "Resistentes al agua",
      "Carga rápida",
    ],
    benefits: [
      "Mejor ajuste",
      "Audio espacial",
      "Resistentes al sudor",
      "Mayor duración de batería",
    ],
  },
  {
    name: "AirPods Pro 2 ANC Réplica",
    description:
      "Audífonos inalámbricos estilo AirPods Pro 2 con cancelación activa de ruido",
    price: 70000,
    stock: 1,
    featured: false,
    ingredients: [
      "Cancelación activa de ruido",
      "Modo transparencia",
      "Audio adaptativo",
      "Puntas de silicona",
    ],
    benefits: [
      "Cancelación de ruido premium",
      "Ajuste perfecto",
      "Audio de alta calidad",
      "Modo ambiente",
    ],
  },
  {
    name: "AirPods 4 ANC Réplica",
    description:
      "Audífonos inalámbricos estilo AirPods 4 con cancelación de ruido",
    price: 76000,
    stock: 1,
    featured: false,
    ingredients: [
      "Última generación",
      "ANC mejorado",
      "Chip H2",
      "Carga USB-C",
    ],
    benefits: [
      "Tecnología más avanzada",
      "Mejor cancelación de ruido",
      "Mayor autonomía",
      "Carga universal USB-C",
    ],
  },
  {
    name: "Buds Pro 2 Réplica",
    description: "Audífonos inalámbricos estilo Galaxy Buds Pro 2",
    price: 70000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño Galaxy Buds Pro 2",
      "ANC inteligente",
      "360 Audio",
      "IPX7",
    ],
    benefits: [
      "Audio envolvente",
      "Cancelación inteligente",
      "Resistentes al agua",
      "Sonido premium",
    ],
  },
  {
    name: "Cargador 25W iPhone",
    description: "Cargador de pared de 25W para iPhone con carga rápida",
    price: 28000,
    stock: 1,
    featured: false,
    ingredients: [
      "Potencia 25W",
      "Carga rápida PD",
      "Compacto",
      "Certificación de seguridad",
    ],
    benefits: [
      "Carga super rápida",
      "Compatible con todos los iPhone",
      "Diseño compacto",
      "Protección integrada",
    ],
  },
  {
    name: "Cable iPhone TC-TC",
    description: "Cable USB-C a USB-C para iPhone con PD de carga rápida",
    price: 11000,
    stock: 1,
    featured: false,
    ingredients: [
      "USB-C a USB-C",
      "Power Delivery",
      "Cable trenzado",
      "1 metro",
    ],
    benefits: [
      "Carga ultra rápida",
      "Doble USB-C",
      "Muy resistente",
      "Compatible con MacBook",
    ],
  },
  {
    name: "Cable TC-iPhone",
    description: "Cable USB-C a Lightning para iPhone",
    price: 7000,
    stock: 1,
    featured: false,
    ingredients: [
      "USB-C a Lightning",
      "Carga rápida",
      "Certificado MFi",
      "Cable resistente",
    ],
    benefits: [
      "Carga y sincronización",
      "Compatible con iPhone",
      "Calidad garantizada",
      "Duradero",
    ],
  },
  {
    name: "Cabeza Cargador 20W iPhone",
    description: "Adaptador de pared USB-C de 20W para iPhone",
    price: 17000,
    stock: 1,
    featured: false,
    ingredients: [
      "Salida 20W USB-C",
      "Power Delivery",
      "Diseño compacto",
      "Múltiples protecciones",
    ],
    benefits: [
      "Carga rápida certificada",
      "Compacto y portátil",
      "Compatible con todos los iPhone",
      "Carga segura",
    ],
  },
  {
    name: "Manos Libres Original iPhone",
    description: "Auriculares con cable EarPods originales para iPhone",
    price: 28000,
    stock: 1,
    featured: false,
    ingredients: [
      "Diseño EarPods",
      "Conector Lightning",
      "Micrófono y controles",
      "Cable resistente",
    ],
    benefits: [
      "Audio balanceado",
      "Control total",
      "Cómodos de usar",
      "Llamadas claras",
    ],
  },
];

async function addProducts() {
  try {
    await mongoose.connect("mongodb://localhost:27017/essence");
    console.log("✅ Conectado a MongoDB");

    for (const productData of products) {
      const product = new Product({
        ...productData,
        category: TECH_CATEGORY_ID,
        image: null,
      });

      await product.save();
      console.log(`✅ Producto creado: ${product.name}`);
    }

    console.log(`\n🎉 ${products.length} productos agregados exitosamente`);
    await mongoose.disconnect();
  } catch (error) {
    console.error("❌ Error:", error);
    process.exit(1);
  }
}

addProducts();
